/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>
#include <string.h>

#include "s21_string.h"

START_TEST(s21_memset_test) {
#line 6
  unsigned char test1[10] = "anna";
  unsigned char test2[10] = "karenina";
  ck_assert_uint_eq((unsigned long)s21_memset(test1, '1', 10),
                    (unsigned long)memset(test1, '1', 10));
  ck_assert_uint_eq((unsigned long)s21_memchr(test1, '3', 10),
                    (unsigned long)memchr(test1, '3', 10));
  ck_assert_uint_eq((unsigned long)s21_memchr(test1, '/', 8),
                    (unsigned long)memchr(test1, '/', 8));
  ck_assert_uint_eq((unsigned long)s21_memchr(test1, '9', 0),
                    (unsigned long)memchr(test1, '9', 0));
  ck_assert_uint_eq((unsigned long)s21_memchr(test1, '0', 4),
                    (unsigned long)memchr(test1, '0', 4));
  ck_assert_uint_eq((unsigned long)s21_memchr(test2, '1', 3),
                    (unsigned long)memchr(test2, '1', 3));
}
END_TEST

START_TEST(s21_memchr_test) {
#line 23
  char test1[] = "12048";
  char test2 = '6';
  char test3 = '3';
  char test4[] = "happy/\0";
  char test5[] = "h";
  char test6 = 'h';
  char test7 = ' ';
  char test8 = '/';
  char test9 = '\0';
  ck_assert_uint_eq((unsigned long)s21_memchr(test1, test2, 6),
                    (unsigned long)memchr(test1, test2, 6));
  ck_assert_uint_eq((unsigned long)s21_memchr(test1, test3, 6),
                    (unsigned long)memchr(test1, test3, 6));
  ck_assert_uint_eq((unsigned long)s21_memchr(test4, test6, 6),
                    (unsigned long)memchr(test4, test6, 6));
  ck_assert_uint_eq((unsigned long)s21_memchr(test5, test7, 1),
                    (unsigned long)memchr(test5, test7, 1));
  ck_assert_uint_eq((unsigned long)s21_memchr(test4, test8, 6),
                    (unsigned long)memchr(test4, test8, 6));
  ck_assert_uint_eq((unsigned long)s21_memchr(test4, test9, 6),
                    (unsigned long)memchr(test4, test9, 6));
}
END_TEST

START_TEST(s21_strlen_test) {
#line 47
  char test_1[] = "12345";
  char test_2[] = "families";
  char test_3[] = "1\0";
  char test_4[] = "   ";
  char test_5[] = "123\0456";
  char test_6[] = "fff\0";
  ck_assert_int_eq(s21_strlen(test_1), strlen(test_1));
  ck_assert_int_eq(s21_strlen(test_2), strlen(test_2));
  ck_assert_int_eq(s21_strlen(test_3), strlen(test_3));
  ck_assert_int_eq(s21_strlen(test_4), strlen(test_4));
  ck_assert_int_eq(s21_strlen(test_5), strlen(test_5));
  ck_assert_int_eq(s21_strlen(test_6), strlen(test_6));
}
END_TEST

START_TEST(s21_memcmp_test) {
#line 61
  char test1[] = "Everything was in confusion in the Oblonskys";
  char test2[] = "Everything was in";
  char test3[] = "\0";
  char test4[] = "every\0 unhappy";
  char test5[] = "every\0 unhappy";
  ck_assert_uint_eq(s21_memcmp(test1, test2, 16) < 0,
                    memcmp(test1, test2, 16) < 0);
  ck_assert_uint_eq(s21_memcmp(test1, test3, 2) > 0,
                    memcmp(test1, test3, 2) > 0);
  ck_assert_uint_eq(s21_memcmp(test2, test3, 2) > 0,
                    memcmp(test2, test3, 2) > 0);
  ck_assert_uint_eq(s21_memcmp(test4, test1, 9) > 0,
                    memcmp(test4, test1, 9) > 0);
  ck_assert_uint_eq(s21_memcmp(test4, test5, 7) == 0,
                    memcmp(test4, test5, 7) == 0);
}
END_TEST

START_TEST(s21_memcpy_test) {
#line 73
  char test_1[10] = "12345";
  char test_2[] = "  ";
  char test_3[20] = "///  ";
  char test_4[] = "   ///";
  char test_5[30] = "";
  char test_6[] = "2222";
  char test_7[] = "123\0123";

  ck_assert_str_eq(s21_memcpy(test_1, test_2, 2), memcpy(test_1, test_2, 2));
  ck_assert_str_eq(s21_memcpy(test_3, test_4, 6), memcpy(test_3, test_4, 6));
  ck_assert_str_eq(s21_memcpy(test_5, test_6, 4), memcpy(test_5, test_6, 4));
  ck_assert_str_eq(s21_memcpy(test_5, test_7, 6), memcpy(test_5, test_7, 6));
}
END_TEST

START_TEST(s21_strncat_test) {
#line 87
  char test_2[4] = "<<<";
  char test_4[2] = "5";
  char test_44[2] = "5";
  char test_5[] = "";

  ck_assert_str_eq(s21_strncat(test_2, test_4, 1), "<<<5");
  ck_assert_str_eq(s21_strncat(test_44, test_5, 0), strncat(test_4, test_5, 0));
}
END_TEST

START_TEST(s21_strstr_test) {
#line 96
  char test_1[] = "<<<5>>>";
  char test_2[] = "5";
  char test_3[] = "StepanArkadyevitchOblonsky";
  char test_4[] = "Stepan";
  char test_5[] = "Darmstadt";
  char test_6[] = "";
  char test_7[] = "Most123unpleasant1234of";
  char test_8[] = "1234";

  ck_assert_ptr_eq(s21_strstr(test_1, test_2), strstr(test_1, test_2));
  ck_assert_ptr_eq(s21_strstr(test_3, test_4), strstr(test_3, test_4));
  ck_assert_ptr_eq(s21_strstr(test_5, test_6), strstr(test_5, test_6));
  ck_assert_ptr_eq(s21_strstr(test_4, test_5), strstr(test_4, test_5));
  ck_assert_ptr_eq(s21_strstr(test_7, test_8), strstr(test_7, test_8));
}
END_TEST

START_TEST(s21_strcspn_test) {
#line 115
  char test1[] = "0123456789";
  char test2[] = "9876";
  char test3[] = "LOST: 4-8-15-16-23-42";
  char test4[] = "1234567890";
  char test5[] = "0/";
  char test6[] = "%%\\#";
  char test7[] = " ";
  char test8[] = "1234567890";
  ck_assert_uint_eq(s21_strcspn(test1, test2), strcspn(test1, test2));
  ck_assert_uint_eq(s21_strcspn(test3, test4), strcspn(test3, test4));
  ck_assert_uint_eq(s21_strcspn(test3, test5), strcspn(test3, test5));
  ck_assert_uint_eq(s21_strcspn(test3, test6), strcspn(test3, test6));
  ck_assert_uint_eq(s21_strcspn(test3, test7), strcspn(test3, test7));
  ck_assert_uint_eq(s21_strcspn(test4, test8), strcspn(test4, test8));
  ck_assert_uint_eq(s21_strcspn(test2, test7), strcspn(test2, test7));
}
END_TEST

START_TEST(s21_strrchr_test) {
#line 132
  char test1[] = "0163456769";
  char test2[] = ";;;;;;H%%//#HH";
  char test3[] = "     /";
  ck_assert_uint_eq((unsigned long)s21_strrchr(test1, '6'),
                    (unsigned long)strrchr(test1, '6'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(test1, ' '),
                    (unsigned long)strrchr(test1, ' '));
  ck_assert_uint_eq((unsigned long)s21_strrchr(test1, '6'),
                    (unsigned long)strrchr(test1, '6'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(test2, 'H'),
                    (unsigned long)strrchr(test2, 'H'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(test2, '$'),
                    (unsigned long)strrchr(test2, '$'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(test2, ';'),
                    (unsigned long)strrchr(test2, ';'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(test3, ' '),
                    (unsigned long)strrchr(test3, ' '));
  ck_assert_str_eq(s21_strrchr(test2, '\0'), strrchr(test2, '\0'));
}
END_TEST

START_TEST(s21_strerror_test) {
#line 156

  ck_assert_str_eq(s21_strerror(0), strerror(0));
  ck_assert_str_eq(s21_strerror(106), strerror(106));
  ck_assert_str_eq(s21_strerror(2147483647), strerror(2147483647));
  ck_assert_str_eq(s21_strerror(-214748364), strerror(-214748364));
}
END_TEST

START_TEST(s21_strchr_test) {
#line 163
  char str1[] = "Frenchwoman";
  int symbol1 = 'w';
  char *ach1 = s21_strchr(str1, symbol1);
  ck_assert_str_eq(ach1, "woman");

  char str2[] = "Frenchwoman";
  int symbol2 = 'w';
  char *ach2 = strchr(str2, symbol2);
  ck_assert_str_eq(ach1, ach2);
  ck_assert_str_eq(str1, str2);

  char str3[] = "Frenchwoman";
  int symbol3 = '\0';
  char *ach3 = s21_strchr(str3, symbol3);

  char str4[] = "Frenchwoman";
  int symbol4 = '\0';
  char *ach4 = strchr(str4, symbol4);
  ck_assert_str_eq(ach3, ach4);
  ck_assert_str_eq(str3, str4);
}
END_TEST

START_TEST(s21_strncpy_test) {
#line 186
  char str1[] = "test of string";
  char dest1[15] = "";

  char str2[] = "test\0";
  char dest2[5] = "";

  ck_assert_str_eq("test ", s21_strncpy(dest1, str1, 5));
  ck_assert_str_eq("test", s21_strncpy(dest2, str2, 4));
}
END_TEST

START_TEST(s21_strpbrk_test) {
#line 202
  char str_for_strpbrk[] = "Megalomania";
  char str_oneof[] = "yal";
  ck_assert_str_eq(s21_strpbrk(str_for_strpbrk, str_oneof), "alomania");
  ck_assert_str_eq(s21_strpbrk(str_for_strpbrk, str_oneof),
                   strpbrk(str_for_strpbrk, str_oneof));

  char *str = "Anna Arkadyevna";
  char *empty = "";
  ck_assert(s21_strpbrk(str, empty) == s21_NULL);
  ck_assert_uint_eq((unsigned long)s21_strpbrk(str, empty),
                    (unsigned long)strpbrk(str, empty));
}
END_TEST

START_TEST(s21_strtok_test) {
#line 214
  char str_strtok1[] = "said/Madame/Karenina(and)again";
  char delim1[] = "/()";

  char str_strtok2[] = "said/Madame/Karenina(and)again";
  char delim2[] = "/()";
  char *my_strtok = s21_strtok(str_strtok1, delim1);
  char *origin_strtok = strtok(str_strtok2, delim2);
  while (my_strtok != s21_NULL) {
    ck_assert_str_eq(my_strtok, origin_strtok);
    my_strtok = s21_strtok(s21_NULL, delim1);
    origin_strtok = strtok(s21_NULL, delim2);
  }
}
END_TEST

START_TEST(s21_strncmp_test) {
#line 228
  char str1[] = "unconsciously 1";
  char str2[] = "unconsciously 3";
  ck_assert_int_eq(s21_strncmp(str1, str2, 5) < 0, strncmp(str1, str2, 5) < 0);
  ck_assert_int_eq(s21_strncmp(str1, str2, 3) == 0,
                   strncmp(str1, str2, 3) == 0);
}
END_TEST

START_TEST(s21_insert_test) {
#line 235
  char *src = "Hello!";
  char *str = ", world";
  char *new_str = s21_insert(src, str, 5);
  if (new_str) {
    ck_assert_str_eq(new_str, "Hello, world!");
    free(new_str);
  }

  new_str = s21_insert(src, "", 15);
  ck_assert(new_str == s21_NULL);

  new_str = s21_insert("Hello!", ", world!!", 5);
  if (new_str) {
    ck_assert_str_eq(new_str, "Hello, world!!!");
    free(new_str);
  }

  new_str = s21_insert("Hello!", ", world!!", 10);
  if (new_str) {
    ck_assert_str_eq(new_str, "Hello!");
    free(new_str);
  }

  new_str = s21_insert("Hello!", ", world!!", 25);
  ck_assert(new_str == s21_NULL);

  new_str = s21_insert("", "", 0);
  if (new_str) {
    ck_assert_str_eq(new_str, "");
    free(new_str);
  }
}
END_TEST

START_TEST(s21_trim_test) {
#line 269
  char string1[] = "QWERTY";
  char string2[] = "123456789";
  char string3[] = "";
  char string4[] = "qwertytest1";
  char string5[] = "QWERTY12345";
  char string6[100] = "       1234567 35432 23456       ";
  char string7[100] = "     1234567   ";
  char string8[100] = "=-=-=-=-==-FINISH -=-=---===";
  char string9[100] = "*ANOTHER CHECK************";
  char string10[100] = "            123456*************";
  char trim1[] = "TYWQ";
  char trim2[] = "13689";
  char trim4[] = "Qwertytest2";
  char trim5[] = "Y1T2R3E4W5Q";
  char trim6[100] = " ";
  char trim8[100] = "-=";
  char trim9[100] = "*ANOTHER ";
  char trim10[100] = "* ";
  char *fin1 = s21_trim(string1, trim1);
  char *fin2 = s21_trim(string2, trim2);
  char *fin3 = s21_trim(string3, trim2);
  char *fin4 = s21_trim(string4, trim4);
  char *fin5 = s21_trim(string5, trim5);
  char *fin6 = s21_trim(string6, trim6);
  char *fin7 = s21_trim(string7, trim6);
  char *fin8 = s21_trim(string8, trim8);
  char *fin9 = s21_trim(string9, trim9);
  char *fin10 = s21_trim(string10, trim10);

  ck_assert_str_eq(fin1, "ER");
  ck_assert_str_eq(fin2, "234567");
  ck_assert_str_eq(fin3, "");
  ck_assert_str_eq(fin4, "qwertytest1");
  ck_assert_str_eq(fin5, "");
  ck_assert_str_eq(fin6, "1234567 35432 23456");
  ck_assert_str_eq(fin7, "1234567");
  ck_assert_str_eq(fin8, "FINISH ");
  ck_assert_str_eq(fin9, "CHECK");
  ck_assert_str_eq(fin10, "123456");
  free(fin1);
  free(fin2);
  free(fin3);
  free(fin4);
  free(fin5);
  free(fin6);
  free(fin7);
  free(fin8);
  free(fin9);
  free(fin10);
}
END_TEST

START_TEST(s21_to_upper_test) {
#line 310
  char str1[] = "konstantin scarcely heard";
  char str2[] = "kAreNIn";

  char *new_str = s21_to_upper(str1);

  if (new_str) {
    ck_assert_str_eq(new_str, "KONSTANTIN SCARCELY HEARD");
    free(new_str);
  }

  new_str = s21_to_upper(str2);

  if (new_str) {
    ck_assert_str_eq(new_str, "KARENIN");
    free(new_str);
  }
}
END_TEST

START_TEST(s21_to_lower_test) {
#line 328
  char str1[] = "KONSTANTIN SCARCELY HEARD";
  char str2[] = "kAreNIn";

  char *new_str = s21_to_lower(str1);

  if (new_str) {
    ck_assert_str_eq(new_str, "konstantin scarcely heard");
    free(new_str);
  }

  new_str = s21_to_lower(str2);

  if (new_str) {
    ck_assert_str_eq(new_str, "karenin");
    free(new_str);
  }
}
END_TEST

START_TEST(sscanf_spec_c_1) {
#line 346
  char str21;
  char str_string;
  char *c = "y";

  int res1 = s21_sscanf(c, "c = %c", &str21);
  int res2 = sscanf(c, "c = %c", &str_string);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(str21, str_string);
}
END_TEST

START_TEST(sscanf_scec_c_3) {
#line 358
  char a, b;
  char *c = "\0";

  int res1 = s21_sscanf(c, "%c", &a);
  int res2 = sscanf(c, "%c", &b);

  ck_assert_int_eq(a, b);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(sscanf_scec_c_4) {
#line 368
  char a, b;
  char *c = "129";

  int res1 = s21_sscanf(c, "%c", &a);
  int res2 = sscanf(c, "%c", &b);

  ck_assert_int_eq(a, b);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(sscanf_spec_d_s) {
#line 378
  char *buff = "Name is Tom and age is 38";
  char name[10];
  char name1[10];
  int age, age1;

  int res1 = s21_sscanf(buff, "Name is %s and age is %d", name, &age);
  int res2 = sscanf(buff, "Name is %s and age is %d", name1, &age1);

  ck_assert_str_eq(name, name1);
  ck_assert_int_eq(age, age1);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(sscanf_spec_d_1) {
#line 391
  int x, y, x1, y1;

  int res1 = s21_sscanf("21 -12", "%d %d", &x, &y);
  int res2 = sscanf("21 -12", "%d %d", &x1, &y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(x, x1);
  ck_assert_int_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_d_2) {
#line 401
  int x, y, x1, y1;

  int res1 = s21_sscanf("21596 -12.89 kk", "%3d %d", &x, &y);
  int res2 = sscanf("21596 -12.89 kk", "%3d %d", &x1, &y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(x, x1);
  ck_assert_int_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_d_4) {
#line 413
  int x, y, x1, y1, c, c1;

  int res1 = s21_sscanf("21596 -12 _", "%3d%d%d", &x, &y, &c);
  int res2 = sscanf("21596 -12 _", "%3d%d%d", &x1, &y1, &c1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(x, x1);
  ck_assert_int_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_f_1) {
#line 423
  float x, y, x1, y1;

  int res1 = s21_sscanf("3.14 -1.23", "%f %f", &x, &y);
  int res2 = sscanf("3.14 -1.23", "%f %f", &x1, &y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(x, x1);
  ck_assert_float_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_f_2) {
#line 433
  float x, y, x1, y1;

  int res1 = s21_sscanf("57.14025 -0.0013", "%7f %f", &x, &y);
  int res2 = sscanf("57.14025 -0.0013", "%7f %f", &x1, &y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(x, x1);
  ck_assert_float_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_f_4) {
#line 444
  float x, x1;

  int res1 = s21_sscanf("265 b", "%f", &x);
  int res2 = sscanf("265 b", "%f", &x1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(x, x1);
}
END_TEST

START_TEST(sscanf_spec_i_2) {
#line 454
  unsigned int a, a1;

  int res1 = s21_sscanf("419", "     %i ", &a);
  int res2 = sscanf("419", "     %i ", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_uint_eq(a, a1);
}
END_TEST

START_TEST(sscanf_spec_e_1) {
#line 463
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.0000000000021 0.0000000000021", "%e %E", &a, &b);
  int res2 = sscanf("0.0000000000021 0.0000000000021", "%e %E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_e_2) {
#line 473
  float a, a1, b, b1;

  int res1 = s21_sscanf("21 21", "%2e %2E", &a, &b);
  int res2 = sscanf("21 21", "%2e %2E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_e_3) {
#line 483
  float a, a1, b, b1;

  int res1 = s21_sscanf("-0.99999999 -0.99999999", "%e %E", &a, &b);
  int res2 = sscanf("-0.99999999 -0.99999999", "%e %E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_e_4) {
#line 493
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.00049 0.000004861", "%e %E", &a, &b);
  int res2 = sscanf("0.00049 0.000004861", "%e %E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_e_5) {
#line 503
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.000000015 0.0054", "%e %E", &a, &b);
  int res2 = sscanf("0.000000015 0.0054", "%e %E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_e_6) {
#line 513
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.123456789 0.00000556", "%e %E", &a, &b);
  int res2 = sscanf("0.123456789 0.00000556", "%e %E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_e_7) {
#line 523
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.000461 -0.00000191", "%e %E", &a, &b);
  int res2 = sscanf("0.000461 -0.00000191", "%e %E", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_1) {
#line 533
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.0000000000021 0.0000000000021", "%g %G", &a, &b);
  int res2 = sscanf("0.0000000000021 0.0000000000021", "%g %G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_2) {
#line 543
  float a, a1, b, b1;

  int res1 = s21_sscanf("21 21", "%2g %2G", &a, &b);
  int res2 = sscanf("21 21", "%2g %2G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_3) {
#line 553
  float a, a1, b, b1;

  int res1 = s21_sscanf("-0.99999999 -0.99999999", "%5g %G", &a, &b);
  int res2 = sscanf("-0.99999999 -0.99999999", "%5g %G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_4) {
#line 563
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.00049 0.000004861", "%g %G", &a, &b);
  int res2 = sscanf("0.00049 0.000004861", "%g %G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_5) {
#line 573
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.000000015 0.0054", "%g %G", &a, &b);
  int res2 = sscanf("0.000000015 0.0054", "%g %G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_6) {
#line 583
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.123456789 0.00000556", "%g %G", &a, &b);
  int res2 = sscanf("0.123456789 0.00000556", "%g %G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_g_7) {
#line 593
  float a, a1, b, b1;

  int res1 = s21_sscanf("0.000461 -0.00000191", "%g %G", &a, &b);
  int res2 = sscanf("0.000461 -0.00000191", "%g %G", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_float_eq(a, a1);
  ck_assert_float_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_o_1) {
#line 603
  unsigned int a, a1, b, b1;

  int res1 = s21_sscanf("077 015 032", "%o %o %*o", &a, &b);
  int res2 = sscanf("077 015 032", "%o %o %*o", &a1, &b1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(a, a1);
  ck_assert_int_eq(b, b1);
}
END_TEST

START_TEST(sscanf_spec_s_1) {
#line 615
  char x[10], y[10], x1[10], y1[10];

  int res1 = s21_sscanf("hi world", "%s %s", x, y);
  int res2 = sscanf("hi world", "%s %s", x1, y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(x, x1);
  ck_assert_str_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_s_2) {
#line 625
  char x[10], y[10], x1[10], y1[10];

  int res1 = s21_sscanf(" hi verter", "%5s %2s", x, y);
  int res2 = sscanf(" hi verter", "%5s %2s", x1, y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(x, x1);
  ck_assert_str_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_u_1) {
#line 635
  unsigned int x, y, x1, y1;

  int res1 = s21_sscanf("4294967295 0", "%u\n%u", &x, &y);
  int res2 = sscanf("4294967295 0", "%u\n%u", &x1, &y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_uint_eq(x, x1);
  ck_assert_uint_eq(y, y1);
}
END_TEST

START_TEST(sscanf_spec_u_2) {
#line 645
  unsigned int x, x1;

  int res1 = s21_sscanf("-1", "%u", &x);
  int res2 = sscanf("-1", "%u", &x1);

  ck_assert_int_eq(res1, res2);
  ck_assert_uint_eq(x, x1);
}
END_TEST

START_TEST(sscanf_spec_n_1) {
#line 657
  unsigned int x, x1, y, y1;

  int res1 = s21_sscanf("1234", "%d%n", &x, &y);
  int res2 = sscanf("1234", "%d%n", &x1, &y1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(x, x1);
  ck_assert_int_eq(y, y1);
}
END_TEST

START_TEST(sscanf_length_2) {
#line 669
  double a, a1;

  int res1 = s21_sscanf("-2.0000001", "%lf", &a);
  int res2 = sscanf("-2.0000001", "%lf", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_double_eq(a, a1);
}
END_TEST

START_TEST(sscanf_length_3) {
#line 678
  short int a, a1;

  int res1 = s21_sscanf("3", "%hi", &a);
  int res2 = sscanf("3", "%hi", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(a, a1);
}
END_TEST

START_TEST(sscanf_length_5) {
#line 688
  long double a, a1;

  int res1 = s21_sscanf("256.14566", "%Lf", &a);
  int res2 = sscanf("256.14566", "%Lf", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_ldouble_eq(a, a1);
}
END_TEST

START_TEST(sscanf_length_6) {
#line 697
  double a, a1;

  int res1 = s21_sscanf("-29.000901", "%lf", &a);
  int res2 = sscanf("-29.000901", "%lf", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_double_eq(a, a1);
}
END_TEST

START_TEST(sscanf_length_7) {
#line 706
  short int a, a1;

  int res1 = s21_sscanf("3", "%1hd", &a);
  int res2 = sscanf("3", "%1hd", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(a, a1);
}
END_TEST

START_TEST(sscanf_length_8) {
#line 715
  short int a, a1;

  int res1 = s21_sscanf(" 015", "%ho", &a);
  int res2 = sscanf(" 015", "%ho", &a1);

  ck_assert_int_eq(res1, res2);
  ck_assert_int_eq(a, a1);
}
END_TEST

START_TEST(sprintf_spec_c_1) {
#line 728
  char str21[80];
  char str_string[80];
  char c = '$';

  int res1 = s21_sprintf(str21, "%-6c", c);
  int res2 = sprintf(str_string, "%-6c", c);
  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_c_2) {
#line 738
  char str21[80];
  char str_string[80];
  char c = '$';

  int res1 = s21_sprintf(str21, "%c%d", c, c);
  int res2 = sprintf(str_string, "%c%d", c, c);
  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_c_3) {
#line 748
  char str21[80];
  char str_string[80];
  char c = 'h', c1 = '^';

  int res1 = s21_sprintf(str21, "%c%3c", c1, c);
  int res2 = sprintf(str_string, "%c%3c", c1, c);
  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_c_4) {
#line 758
  char str21[80];
  char str_string[80];
  char c = 255, c1 = 19;

  int res1 = s21_sprintf(str21, "%c %8c", c, c1);
  int res2 = sprintf(str_string, "%c %8c", c, c1);
  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_c_5) {
#line 768
  char str21[80];
  char str_string[80];
  char c = '0', c1 = 0;

  int res1 = s21_sprintf(str21, "%c %c", c, c1);
  int res2 = sprintf(str_string, "%c %c", c, c1);
  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_c_6) {
#line 778
  char str21[80];
  char str_string[80];
  char c = '\0';

  int res1 = s21_sprintf(str21, "%c", c);
  int res2 = sprintf(str_string, "%c", c);
  ck_assert_int_eq(res1, res2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_1) {
#line 789
  char str21[80];
  char str_string[80];
  int a = -21, b = 5;

  int res3 = s21_sprintf(str21, "%+d %+-d", a, b);
  int res4 = sprintf(str_string, "%+d %+-d", a, b);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_2) {
#line 799
  char str21[80];
  char str_string[80];
  int a = -21, b = 5;

  int res3 = s21_sprintf(str21, "%d + % d = %d", a, b, a + b);
  int res4 = sprintf(str_string, "%d + % d = %d", a, b, a + b);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_3) {
#line 809
  char str21[80];
  char str_string[80];
  int b = 5;

  int res3 = s21_sprintf(str21, "%4.d, %4.13d", b, 151258786);
  int res4 = sprintf(str_string, "%4.d, %4.13d", b, 151258786);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_3_1) {
#line 819
  char str21[80];
  char str_string[80];
  int b = 0;

  int res3 = s21_sprintf(str21, "%1.0d, %13.4d", b, 151258786);
  int res4 = sprintf(str_string, "%1.0d, %13.4d", b, 151258786);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_4) {
#line 829
  char str21[80];
  char str_string[80];
  int a = -21;

  int res3 = s21_sprintf(str21, "%-6d", a);
  int res4 = sprintf(str_string, "%-6d", a);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_5) {
#line 839
  char str21[80];
  char str_string[80];
  int a = -21;

  int res3 = s21_sprintf(str21, "% d", a * -1);
  int res4 = sprintf(str_string, "% d", a * -1);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_6) {
#line 849
  char str21[80];
  char str_string[80];
  int a = 2147483647;

  int res3 = s21_sprintf(str21, "%+.0d %d", a, a * -1);
  int res4 = sprintf(str_string, "%+.0d %d", a, a * -1);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_7) {
#line 859
  char str21[80];
  char str_string[80];
  int a = -21;

  int res3 = s21_sprintf(str21, "%-6d", a);
  int res4 = sprintf(str_string, "%-6d", a);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_d_8) {
#line 869
  char str21[80];
  char str_string[80];
  int a = 2147483647, b = 0;

  int res3 = s21_sprintf(str21, "%+-12.12d\n%+-12.12d", a, b);
  int res4 = sprintf(str_string, "%+-12.12d\n%+-12.12d", a, b);
  ck_assert_int_eq(res3, res4);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i) {
#line 879
  char str21[80];
  char str_string[80];
  unsigned int a = 419;

  int res5 = s21_sprintf(str21, "%i", a);
  int res6 = sprintf(str_string, "%i", a);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i_2) {
#line 889
  char str21[80];
  char str_string[80];
  unsigned int a = 0xA;

  int res5 = s21_sprintf(str21, "% i", a);
  int res6 = sprintf(str_string, "% i", a);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i_3) {
#line 899
  char str21[80];
  char str_string[80];
  unsigned int a = 4294967295, b = 0;

  int res5 = s21_sprintf(str21, "%+i%i", a, b);
  int res6 = sprintf(str_string, "%+i%i", a, b);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i_4) {
#line 909
  char str21[80];
  char str_string[80];
  unsigned int a = 42977;

  int res5 = s21_sprintf(str21, "%-8i", a);
  int res6 = sprintf(str_string, "%-8i", a);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i_5) {
#line 919
  char str21[80];
  char str_string[80];
  unsigned int a = 42977;

  int res5 = s21_sprintf(str21, "%6.6i", a);
  int res6 = sprintf(str_string, "%6.6i", a);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i_6) {
#line 929
  char str21[80];
  char str_string[80];
  unsigned int a = 0;

  int res5 = s21_sprintf(str21, "%1.0i", a);
  int res6 = sprintf(str_string, "%1.0i", a);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_i_7) {
#line 939
  char str21[80];
  char str_string[80];
  unsigned int a = 077;

  int res5 = s21_sprintf(str21, "%018i", a);
  int res6 = sprintf(str_string, "%018i", a);
  ck_assert_int_eq(res5, res6);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_1) {
#line 949
  char str21[80];
  char str_string[80];
  float e = 0.0000000000021;

  int res7 = s21_sprintf(str21, "%e = %E", e, e);
  int res8 = sprintf(str_string, "%e = %E", e, e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_2) {
#line 959
  char str21[80];
  char str_string[80];
  float i = 11;

  int res7 = s21_sprintf(str21, "%#e", i);
  int res8 = sprintf(str_string, "%#e", i);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_3) {
#line 969
  char str21[80];
  char str_string[80];
  float e = 0.0000021;

  int res7 = s21_sprintf(str21, "%+e = %#E", e, e);
  int res8 = sprintf(str_string, "%+e = %#E", e, e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_4) {
#line 979
  char str21[80];
  char str_string[80];
  float e = 0.0021;

  int res7 = s21_sprintf(str21, "%08e = %-8E", e, e);
  int res8 = sprintf(str_string, "%08e = %-8E", e, e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_5) {
#line 989
  char str21[80];
  char str_string[80];
  float e = -0.99999999;

  int res7 = s21_sprintf(str21, "%20e %+E", e, e);
  int res8 = sprintf(str_string, "%20e %+E", e, e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_6) {
#line 999
  char str21[80];
  char str_string[80];
  float e = 0.00049, e1 = 0.000004861;

  int res7 = s21_sprintf(str21, "%e %E", e, e1);
  int res8 = sprintf(str_string, "%e %E", e, e1);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_7) {
#line 1009
  char str21[80];
  char str_string[80];
  float e = 0.000000015, e1 = 0.0054;

  int res7 = s21_sprintf(str21, "%5.0e %.5E", e, e1);
  int res8 = sprintf(str_string, "%5.0e %.5E", e, e1);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_8) {
#line 1019
  char str21[80];
  char str_string[80];
  float e = 0.123456789, e1 = 0.00000556;

  int res7 = s21_sprintf(str21, "%e %E", e, e1);
  int res8 = sprintf(str_string, "%e %E", e, e1);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_e_9) {
#line 1029
  char str21[80];
  char str_string[80];
  float e = 0.000461, e1 = -0.00000191;

  int res7 = s21_sprintf(str21, "%.*e %.*E", 4, e, 7, e1);
  int res8 = sprintf(str_string, "%.*e %.*E", 4, e, 7, e1);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_1) {
#line 1039
  char str21[80];
  char str_string[80];
  float b = 3.1416, e = 0.759321;

  int res9 = s21_sprintf(str21, "%8.4f\n%f", e, b);
  int res10 = sprintf(str_string, "%8.4f\n%f", e, b);
  ck_assert_int_eq(res9, res10);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_2) {
#line 1049
  char str21[80];
  char str_string[80];

  int res9 = s21_sprintf(str21, "%04f", 13.0);
  int res10 = sprintf(str_string, "%04f", 13.0);
  ck_assert_int_eq(res9, res10);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_3) {
#line 1058
  char str21[80];
  char str_string[80];
  float b = 3.1416;

  int res9 = s21_sprintf(str21, "%.*f", 2, b);
  int res10 = sprintf(str_string, "%.*f", 2, b);
  ck_assert_int_eq(res9, res10);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_4) {
#line 1068
  char str21[80];
  char str_string[80];
  float e = 0.00000021;

  int res7 = s21_sprintf(str21, "% f", e);
  int res8 = sprintf(str_string, "% f", e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_5) {
#line 1078
  char str21[80];
  char str_string[80];
  float e = 0.0;

  int res7 = s21_sprintf(str21, "%1.0f", e);
  int res8 = sprintf(str_string, "%1.0f", e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_6) {
#line 1088
  char str21[80];
  char str_string[80];
  float e = 25879233.85651;

  int res7 = s21_sprintf(str21, "%3.12f %16.2f", e, e);
  int res8 = sprintf(str_string, "%3.12f %16.2f", e, e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_7) {
#line 1098
  char str21[80];
  char str_string[80];
  float e = 2587965433.85651;

  int res7 = s21_sprintf(str21, "%03.12f %016.2f", e, e);
  int res8 = sprintf(str_string, "%03.12f %016.2f", e, e);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_8) {
#line 1108
  char str21[80];
  char str_string[80];
  float e = 25233.85651, k = 1.5878844328;

  int res7 = s21_sprintf(str21, "%-2f %-25f / %-2f %-25f", e, e, k, k);
  int res8 = sprintf(str_string, "%-2f %-25f / %-2f %-25f", e, e, k, k);
  ck_assert_int_eq(res7, res8);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_f_9) {
#line 1118
  char str21[80];
  char str_string[80];
  float e = -25.4548;

  int res7 = s21_sprintf(str21, "%.2f %+-f", e, e);
  int res8 = sprintf(str_string, "%.2f %+-f", e, e);
  ck_assert_int_eq(res7, res8);
}
END_TEST

START_TEST(sprintf_spec_f_10) {
#line 1127
  char str21[80];
  char str_string[80];
  float e = -25.0;

  int res7 = s21_sprintf(str21, "%f%f", e, e);
  int res8 = sprintf(str_string, "%f%f", e, e);
  ck_assert_int_eq(res7, res8);
}
END_TEST

START_TEST(sprintf_spec_o) {
#line 1139
  char str21[80];
  char str_string[80];
  unsigned int a = 4194965695;

  int res13 = s21_sprintf(str21, "%o", a);
  int res14 = sprintf(str_string, "%o", a);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_o_2) {
#line 1149
  char str21[80];
  char str_string[80];
  unsigned int a = 077;

  int res13 = s21_sprintf(str21, "%o", a);
  int res14 = sprintf(str_string, "%o", a);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_o_3) {
#line 1159
  char str21[80];
  char str_string[80];
  unsigned int a = 077;

  int res13 = s21_sprintf(str21, "%-5o %05o", a, a);
  int res14 = sprintf(str_string, "%-5o %05o", a, a);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_o_4) {
#line 1169
  char str21[80];
  char str_string[80];
  unsigned int a = 077;

  int res13 = s21_sprintf(str21, "%#o", a);
  int res14 = sprintf(str_string, "%#o", a);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_p) {
#line 1179
  char str21[80];
  char str_string[80];
  char *s = "Verter Verter";

  int res13 = s21_sprintf(str21, "address of %s is %p", s, &s);
  int res14 = sprintf(str_string, "address of %s is %p", s, &s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_p_2) {
#line 1189
  char str21[80];
  char str_string[80];
  char *s = "Verter 08&^C 45_}pk";

  int res13 = s21_sprintf(str21, "address of %s is %p", s, &s);
  int res14 = sprintf(str_string, "address of %s is %p", s, &s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_p_3) {
#line 1199
  char str21[80];
  char str_string[80];
  char *s =
      "/!%g yp $"
      "ffds.:;";

  int res13 = s21_sprintf(str21, "address of %s is %p", s, &s);
  int res14 = sprintf(str_string, "address of %s is %p", s, &s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_p_4) {
#line 1209
  char str21[80];
  char str_string[80];
  char *s = "";

  int res13 = s21_sprintf(str21, "address of %s is %p", s, &s);
  int res14 = sprintf(str_string, "address of %s is %p", s, &s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_p_5) {
#line 1219
  char str21[80];
  char str_string[80];
  char *s = "\0";

  int res13 = s21_sprintf(str21, "address of %s is %p", s, &s);
  int res14 = sprintf(str_string, "address of %s is %p", s, &s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_p_6) {
#line 1229
  char str21[80];
  char str_string[80];
  char s[] = {'h', 'i', '\0'};

  int res13 = s21_sprintf(str21, "address of %s is %p", s, &s);
  int res14 = sprintf(str_string, "address of %s is %p", s, &s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_7) {
#line 1239
  char str21[80];
  char str_string[80];
  char s[5] = {0};

  int res13 = s21_sprintf(str21, "address of %s", s);
  int res14 = sprintf(str_string, "address of %s", s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_s_8) {
#line 1249
  char str21[80];
  char str_string[80];
  char *s = "Hi hi02_a!^";

  int res13 = s21_sprintf(str21, "%3.5s%s - %s%-13s", s, s, s, s);
  int res14 = sprintf(str_string, "%3.5s%s - %s%-13s", s, s, s, s);
  ck_assert_int_eq(res13, res14);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_u_1) {
#line 1259
  char str21[80];
  char str_string[80];
  unsigned int u = 4294967295, a = 45;

  int res15 = s21_sprintf(str21, "%u %u", u, a);
  int res16 = sprintf(str_string, "%u %u", u, a);
  ck_assert_int_eq(res15, res16);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_u_2) {
#line 1269
  char str21[80];
  char str_string[80];

  int res23 = s21_sprintf(str21, "%u", 0);
  int res24 = sprintf(str_string, "%u", 0);
  ck_assert_int_eq(res23, res24);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_u_3) {
#line 1278
  char str21[80];
  char str_string[80];

  int res23 = s21_sprintf(str21, "%u", -15);
  int res24 = sprintf(str_string, "%u", -15);
  ck_assert_int_eq(res23, res24);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_u_4) {
#line 1287
  char str21[80];
  char str_string[80];
  unsigned int u = 4294967295, a = 45;

  int res15 = s21_sprintf(str21, "%12.2u %1.6u", u, a);
  int res16 = sprintf(str_string, "%12.2u %1.6u", u, a);
  ck_assert_int_eq(res15, res16);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_u_5) {
#line 1297
  char str21[80];
  char str_string[80];
  unsigned int u = 4294967295, a = 45;

  int res15 = s21_sprintf(str21, "%-12.2u %1.6u", a, u);
  int res16 = sprintf(str_string, "%-12.2u %1.6u", a, u);
  ck_assert_int_eq(res15, res16);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_u_6) {
#line 1307
  char str21[80];
  char str_string[80];
  unsigned int u = 4294967295, a = 45;

  int res15 = s21_sprintf(str21, "%12.2u %-1.6u %05u %1.6u", a, a, u, u);
  int res16 = sprintf(str_string, "%12.2u %-1.6u %05u %1.6u", a, a, u, u);
  ck_assert_int_eq(res15, res16);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_x) {
#line 1317
  char str21[80];
  char str_string[80];
  unsigned int a = 4194965695;

  int res17 = s21_sprintf(str21, "%#x = %X", a, a);
  int res18 = sprintf(str_string, "%#x = %X", a, a);
  ck_assert_int_eq(res17, res18);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_x_3) {
#line 1329
  char str21[80];
  char str_string[80];
  unsigned int a = 0xFFAACCBBU;

  int res17 = s21_sprintf(str21, "%-7.13x = %010X", a, a);
  int res18 = sprintf(str_string, "%-7.13x = %010X", a, a);
  ck_assert_int_eq(res17, res18);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_n) {
#line 1339
  char str21[80];
  char str_string[80];
  int n1;
  int n2;

  int res19 = s21_sprintf(str21, "thisis7%n", &n1);
  int res20 = sprintf(str_string, "thisis7%n", &n2);
  ck_assert_int_eq(res19, res20);
  ck_assert_int_eq(n1, n2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_n_2) {
#line 1351
  char str21[80];
  char str_string[80];
  int n1;
  int n2;

  int res19 = s21_sprintf(str21, "%n", &n1);
  int res20 = sprintf(str_string, "%n", &n2);
  ck_assert_int_eq(res19, res20);
  ck_assert_int_eq(n1, n2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_n_3) {
#line 1363
  char str21[80];
  char str_string[80];
  int n1;
  int n2;

  int res19 = s21_sprintf(str21, "%%%n", &n1);
  int res20 = sprintf(str_string, "%%%n", &n2);
  ck_assert_int_eq(res19, res20);
  ck_assert_int_eq(n1, n2);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_proc) {
#line 1375
  char str21[80];
  char str_string[80];

  int res21 = s21_sprintf(str21, "%%");
  int res22 = sprintf(str_string, "%%");
  ck_assert_int_eq(res21, res22);
  ck_assert_str_eq(str21, str_string);
}
END_TEST

START_TEST(sprintf_spec_length_1) {
#line 1384
  char str21[80];
  char str_string[80];
  long double v = 413615.131513511151551;

  int res23 = s21_sprintf(str21, "%Lf", v);
  int res24 = sprintf(str_string, "%Lf", v);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_2) {
#line 1394
  char str21[80];
  char str_string[80];
  double f = -2.0000001;

  int res23 = s21_sprintf(str21, "%.4lf", f);
  int res24 = sprintf(str_string, "%.4lf", f);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_3) {
#line 1404
  char str21[80];
  char str_string[80];
  short int h = 3;

  int res23 = s21_sprintf(str21, "%03hi", h);
  int res24 = sprintf(str_string, "%03hi", h);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_6) {
#line 1417
  char str21[80];
  char str_string[80];
  double f = -29.000901;

  int res23 = s21_sprintf(str21, "%-6.4lf", f);
  int res24 = sprintf(str_string, "%-6.4lf", f);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_7) {
#line 1428
  char str21[80];
  char str_string[80];
  double f = 29.000901;

  int res23 = s21_sprintf(str21, "%+1.11lf", f);
  int res24 = sprintf(str_string, "%+1.11lf", f);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_8) {
#line 1438
  char str21[80];
  char str_string[80];
  short int h = 3;

  int res23 = s21_sprintf(str21, "%-3.2hd", h);
  int res24 = sprintf(str_string, "%-3.2hd", h);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_9) {
#line 1448
  char str21[80];
  char str_string[80];
  short int h = 015;

  int res23 = s21_sprintf(str21, "%#ho", h);
  int res24 = sprintf(str_string, "%#ho", h);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_10) {
#line 1458
  char str21[80];
  char str_string[80];
  short int h = 15;

  int res23 = s21_sprintf(str21, "%hu%%%hu", h, h);
  int res24 = sprintf(str_string, "%hu%%%hu", h, h);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_11) {
#line 1468
  char str21[80];
  char str_string[80];
  short int h = 0xa;

  int res23 = s21_sprintf(str21, "%hx / %#hX", h, h);
  int res24 = sprintf(str_string, "%hx / %#hX", h, h);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_12) {
#line 1478
  char str21[80];
  char str_string[80];
  long unsigned int v = 0xA45F0D;

  int res23 = s21_sprintf(str21, "%5lX %-10lx", v, v);
  int res24 = sprintf(str_string, "%5lX %-10lx", v, v);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_13) {
#line 1488
  char str21[80];
  char str_string[80];
  long double v = 0.0000002453;

  int res23 = s21_sprintf(str21, "%-.8LE", v);
  int res24 = sprintf(str_string, "%-.8LE", v);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_14) {
#line 1498
  char str21[80];
  char str_string[80];
  long double v = 0.01000098;

  int res23 = s21_sprintf(str21, "%08.3Lg - %.6LG", v, v);
  int res24 = sprintf(str_string, "%08.3Lg - %.6LG", v, v);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_17) {
#line 1510
  char str21[400];
  char str_string[400];
  wchar_t charX[] = L"🥳урааааааяу😀";

  int res23 = s21_sprintf(str21, "%ls", charX);
  int res24 = sprintf(str_string, "%ls", charX);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

START_TEST(sprintf_spec_length_18) {
#line 1521
  char str21[80];
  char str_string[80];
  wchar_t charX = L'🥳';

  int res23 = s21_sprintf(str21, "%lc", charX);
  int res24 = sprintf(str_string, "%lc", charX);
  ck_assert_str_eq(str21, str_string);
  ck_assert_int_eq(res23, res24);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_memset_test);
  tcase_add_test(tc1_1, s21_memchr_test);
  tcase_add_test(tc1_1, s21_strlen_test);
  tcase_add_test(tc1_1, s21_memcmp_test);
  tcase_add_test(tc1_1, s21_memcpy_test);
  tcase_add_test(tc1_1, s21_strncat_test);
  tcase_add_test(tc1_1, s21_strstr_test);
  tcase_add_test(tc1_1, s21_strcspn_test);
  tcase_add_test(tc1_1, s21_strrchr_test);
  tcase_add_test(tc1_1, s21_strerror_test);
  tcase_add_test(tc1_1, s21_strchr_test);
  tcase_add_test(tc1_1, s21_strncpy_test);
  tcase_add_test(tc1_1, s21_strpbrk_test);
  tcase_add_test(tc1_1, s21_strtok_test);
  tcase_add_test(tc1_1, s21_strncmp_test);
  tcase_add_test(tc1_1, s21_insert_test);
  tcase_add_test(tc1_1, s21_trim_test);
  tcase_add_test(tc1_1, s21_to_upper_test);
  tcase_add_test(tc1_1, s21_to_lower_test);
  tcase_add_test(tc1_1, sscanf_spec_c_1);
  tcase_add_test(tc1_1, sscanf_scec_c_3);
  tcase_add_test(tc1_1, sscanf_scec_c_4);
  tcase_add_test(tc1_1, sscanf_spec_d_s);
  tcase_add_test(tc1_1, sscanf_spec_d_1);
  tcase_add_test(tc1_1, sscanf_spec_d_2);
  tcase_add_test(tc1_1, sscanf_spec_d_4);
  tcase_add_test(tc1_1, sscanf_spec_f_1);
  tcase_add_test(tc1_1, sscanf_spec_f_2);
  tcase_add_test(tc1_1, sscanf_spec_f_4);
  tcase_add_test(tc1_1, sscanf_spec_i_2);
  tcase_add_test(tc1_1, sscanf_spec_e_1);
  tcase_add_test(tc1_1, sscanf_spec_e_2);
  tcase_add_test(tc1_1, sscanf_spec_e_3);
  tcase_add_test(tc1_1, sscanf_spec_e_4);
  tcase_add_test(tc1_1, sscanf_spec_e_5);
  tcase_add_test(tc1_1, sscanf_spec_e_6);
  tcase_add_test(tc1_1, sscanf_spec_e_7);
  tcase_add_test(tc1_1, sscanf_spec_g_1);
  tcase_add_test(tc1_1, sscanf_spec_g_2);
  tcase_add_test(tc1_1, sscanf_spec_g_3);
  tcase_add_test(tc1_1, sscanf_spec_g_4);
  tcase_add_test(tc1_1, sscanf_spec_g_5);
  tcase_add_test(tc1_1, sscanf_spec_g_6);
  tcase_add_test(tc1_1, sscanf_spec_g_7);
  tcase_add_test(tc1_1, sscanf_spec_o_1);
  tcase_add_test(tc1_1, sscanf_spec_s_1);
  tcase_add_test(tc1_1, sscanf_spec_s_2);
  tcase_add_test(tc1_1, sscanf_spec_u_1);
  tcase_add_test(tc1_1, sscanf_spec_u_2);
  tcase_add_test(tc1_1, sscanf_spec_n_1);
  tcase_add_test(tc1_1, sscanf_length_2);
  tcase_add_test(tc1_1, sscanf_length_3);
  tcase_add_test(tc1_1, sscanf_length_5);
  tcase_add_test(tc1_1, sscanf_length_6);
  tcase_add_test(tc1_1, sscanf_length_7);
  tcase_add_test(tc1_1, sscanf_length_8);
  tcase_add_test(tc1_1, sprintf_spec_c_1);
  tcase_add_test(tc1_1, sprintf_spec_c_2);
  tcase_add_test(tc1_1, sprintf_spec_c_3);
  tcase_add_test(tc1_1, sprintf_spec_c_4);
  tcase_add_test(tc1_1, sprintf_spec_c_5);
  tcase_add_test(tc1_1, sprintf_spec_c_6);
  tcase_add_test(tc1_1, sprintf_spec_d_1);
  tcase_add_test(tc1_1, sprintf_spec_d_2);
  tcase_add_test(tc1_1, sprintf_spec_d_3);
  tcase_add_test(tc1_1, sprintf_spec_d_3_1);
  tcase_add_test(tc1_1, sprintf_spec_d_4);
  tcase_add_test(tc1_1, sprintf_spec_d_5);
  tcase_add_test(tc1_1, sprintf_spec_d_6);
  tcase_add_test(tc1_1, sprintf_spec_d_7);
  tcase_add_test(tc1_1, sprintf_spec_d_8);
  tcase_add_test(tc1_1, sprintf_spec_i);
  tcase_add_test(tc1_1, sprintf_spec_i_2);
  tcase_add_test(tc1_1, sprintf_spec_i_3);
  tcase_add_test(tc1_1, sprintf_spec_i_4);
  tcase_add_test(tc1_1, sprintf_spec_i_5);
  tcase_add_test(tc1_1, sprintf_spec_i_6);
  tcase_add_test(tc1_1, sprintf_spec_i_7);
  tcase_add_test(tc1_1, sprintf_spec_e_1);
  tcase_add_test(tc1_1, sprintf_spec_e_2);
  tcase_add_test(tc1_1, sprintf_spec_e_3);
  tcase_add_test(tc1_1, sprintf_spec_e_4);
  tcase_add_test(tc1_1, sprintf_spec_e_5);
  tcase_add_test(tc1_1, sprintf_spec_e_6);
  tcase_add_test(tc1_1, sprintf_spec_e_7);
  tcase_add_test(tc1_1, sprintf_spec_e_8);
  tcase_add_test(tc1_1, sprintf_spec_e_9);
  tcase_add_test(tc1_1, sprintf_spec_f_1);
  tcase_add_test(tc1_1, sprintf_spec_f_2);
  tcase_add_test(tc1_1, sprintf_spec_f_3);
  tcase_add_test(tc1_1, sprintf_spec_f_4);
  tcase_add_test(tc1_1, sprintf_spec_f_5);
  tcase_add_test(tc1_1, sprintf_spec_f_6);
  tcase_add_test(tc1_1, sprintf_spec_f_7);
  tcase_add_test(tc1_1, sprintf_spec_f_8);
  tcase_add_test(tc1_1, sprintf_spec_f_9);
  tcase_add_test(tc1_1, sprintf_spec_f_10);
  tcase_add_test(tc1_1, sprintf_spec_o);
  tcase_add_test(tc1_1, sprintf_spec_o_2);
  tcase_add_test(tc1_1, sprintf_spec_o_3);
  tcase_add_test(tc1_1, sprintf_spec_o_4);
  tcase_add_test(tc1_1, sprintf_spec_s_p);
  tcase_add_test(tc1_1, sprintf_spec_s_p_2);
  tcase_add_test(tc1_1, sprintf_spec_s_p_3);
  tcase_add_test(tc1_1, sprintf_spec_s_p_4);
  tcase_add_test(tc1_1, sprintf_spec_s_p_5);
  tcase_add_test(tc1_1, sprintf_spec_s_p_6);
  tcase_add_test(tc1_1, sprintf_spec_s_7);
  tcase_add_test(tc1_1, sprintf_spec_s_8);
  tcase_add_test(tc1_1, sprintf_spec_u_1);
  tcase_add_test(tc1_1, sprintf_spec_u_2);
  tcase_add_test(tc1_1, sprintf_spec_u_3);
  tcase_add_test(tc1_1, sprintf_spec_u_4);
  tcase_add_test(tc1_1, sprintf_spec_u_5);
  tcase_add_test(tc1_1, sprintf_spec_u_6);
  tcase_add_test(tc1_1, sprintf_spec_x);
  tcase_add_test(tc1_1, sprintf_spec_x_3);
  tcase_add_test(tc1_1, sprintf_spec_n);
  tcase_add_test(tc1_1, sprintf_spec_n_2);
  tcase_add_test(tc1_1, sprintf_spec_n_3);
  tcase_add_test(tc1_1, sprintf_spec_proc);
  tcase_add_test(tc1_1, sprintf_spec_length_1);
  tcase_add_test(tc1_1, sprintf_spec_length_2);
  tcase_add_test(tc1_1, sprintf_spec_length_3);
  tcase_add_test(tc1_1, sprintf_spec_length_6);
  tcase_add_test(tc1_1, sprintf_spec_length_7);
  tcase_add_test(tc1_1, sprintf_spec_length_8);
  tcase_add_test(tc1_1, sprintf_spec_length_9);
  tcase_add_test(tc1_1, sprintf_spec_length_10);
  tcase_add_test(tc1_1, sprintf_spec_length_11);
  tcase_add_test(tc1_1, sprintf_spec_length_12);
  tcase_add_test(tc1_1, sprintf_spec_length_13);
  tcase_add_test(tc1_1, sprintf_spec_length_14);
  tcase_add_test(tc1_1, sprintf_spec_length_17);
  tcase_add_test(tc1_1, sprintf_spec_length_18);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
